<?
include_once($_SERVER['DOCUMENT_ROOT']."/incom/modules/general/mysql.php");
include_once($_SERVER['DOCUMENT_ROOT']."/incom/modules/general/api.php");
$_SESSION["version"]=$_GET["lang"];
if(@$_GET['id'])
{
	$ob->delete_tree(@$_GET['id'],"block");
}
?>
<script>
window.parent.location.reload();
</script>