/*
SWFAddress Plugin v1.3 BETA 2 for KRPanoJS and iOS4.2+
by Jaydee || http://jaydee.ru/
*/
var krpanoplugin=function(){function g(){var a=SWFAddress.getPath();"/"!=a&&d.call(r(c.onpathchange,a))}function s(){var a=SWFAddress.getPath();if(t&&(!a||""==a))a="/";p||(p=K());var b="/"==a,e=b&&p?n("pano",p).pageurl:a,e=q(e);b&&!t&&SWFAddress.setHistory(!1);u[e]?(b=n("pano",u[e]),a=b.xmlurl||b.scene,b=b.scene?"scene":"xml",a&&(a!=d.get("xml.url")||a!=d.get("xml.scene"))&&d.call(r(c.onurlchange,e,a,b))):d.call(r(c.onurlchange,a));d.call(c.onparamschange)}function B(a){var b=c.onshortensuccess,b=
b.replace(/\%URL\%/gi,a);d.call(b)}function C(a){switch(a){case BitlyService.ERROR_LOGIN_OR_APIKEY_UNDEFINED:a="Bit.ly Login and API Key must be defined.";break;case BitlyService.ERROR_UNABLE_CONNECT_TO_SERVICE:a="Unable connect to Bit.ly service.";break;case BitlyService.ERROR_WRONG_SANDBOX:a="Unable to shorten local URL.";break;case BitlyService.ERROR_SHORTEN_ERROR:a="Bit.ly service is unable to shorten specified URL for some reason.";break;default:case BitlyService.ERROR_UNKNOWN:a="Unknown error occured."}l("Shorten error - "+
a,3);d.call(c.onshortenerror)}function f(){}function m(a){L(a)}function D(){return SWFAddress.getPath()}function X(a){SWFAddress.setTitle(a)}function M(){return SWFAddress.getTitle()}function N(){return SWFAddress.getValue()}function E(){var a=y(),b=a.indexOf("#"),b=-1==b?a.length:b;return a.substring(0,b)}function Y(){return y()}function O(){return escape(y())}function F(){return E()+"#"+D()+"?ath="+z.hlookat+"&atv="+z.vlookat+"&fov="+z.fov}function P(){return escape(F())}function Q(){return 0!=
SWFAddress.getParameterNames().length}function R(){return SWFAddress.getQueryString()}function Z(a){k.apiKey=a}function $(){return k.apiKey}function aa(a){k.login=a}function ba(){return k.login}function ca(){return t}function da(){return G}function ea(){var a=d.get("xml.url")||d.get("xml.scene");if((a=a?a.toLowerCase():null)&&H!=a)if(H=a,a=v[H]){if(a){var b=n("pano",a),e=b.pageurl,j=b.pagetitle;e&&L(e);if(j){var b=c.titleprefix,e=c.titlepostfix,h=j;j.match(S)&&(h=d.get(S.exec(j)[1]));j=h;b=b?b+j:
j;SWFAddress.setTitle(e?b+e:b)}}SWFAddress.getHistory()||SWFAddress.setHistory(!0);a=n("pano",a);d.call(a.onxmlcomplete)}}function fa(a,b,e,c,d,g){a=h(a);b=h(b);e=w(e);c=h(c);d=h(d);g=h(g);T(a,b,e,c,d,g)}function ga(a){a=h(a);U(a)}function ha(){for(var a in v)U(a)}function ia(a){(a=h(a))?k.shorten(a):l("Shorten Error - URL must be specified.",3)}function ja(){s(null);g(null)}function ka(a,b){var e=h(a),c=h(b);e&&c?d.set(c,String(SWFAddress.getParameter(e))):l("Get Param Error - Parameter name and target variable name must be specified.",
3)}function la(a,b,e){a=h(a);b=h(b);e=w(e);if(a){for(var c=SWFAddress.getParameterNames(),d=[],g=0;g<c.length;g++){var m=c[g],f=SWFAddress.getParameter(m);"string"==typeof f&&(f=[f]);m==a&&(f=null===b||""==b?[]:e?f.concat([b]):[b]);for(var k=0;k<f.length;k++)d.push(m+"="+f[k])}-1==c.indexOf(a)&&d.push(a+"="+b);I(d.join("&"))}else l("Set Param Error - Parameter name must be specified.",3)}function ma(){for(var a,b,c="",d=0;d<arguments.length;d+=2)a=h(arguments[d]),b=h(arguments[d+1]),a?b&&(c+=a+"="+
b+"&"):l("Set Params Error - Parameters name must be specified.",3);c.length&&(c=c.substr(0,c.length-1));I(c)}function na(){I(null)}function oa(a,b,c,j){a=h(a);b=h(b);c=h(c);j=h(j);(a=d.get(a))&&null!=a?c&&j?(j=a.replace(c,j),d.set(b,j)):l("Replace Error - Pattern and replacement must be specified.",3):l("Replace Error - Source string is null.",3)}function pa(a,b){var c=h(a),j=h(b);c&&j?d.set(j,c.replace(/\&amp\;/gi,"&")):l("Replace Ampersands Error - Source string & destination variable must be defined.",
3)}function T(a,b,e,j,g,h,f){if(a&&b&&j){var m=d.parsePath(b).toLowerCase();f=f||!0;j=q(j);v[m]=a;u[j]=a;f&&(a=c.createarray("pano").createItem(a),e?a.scene=b:a.xmlurl=b,a.pageurl=j,a.pagetitle=g,a.onxmlcomplete=h)}else l("Add Pano Error - Unable to add pano with name ["+a+"]: name, XML URL or Scene name and Page URL must be specified.",3)}function U(a){if(a){var b=n("pano",a);if(b){var e=d.parsePath(b.xmlurl||b.scene).toLowerCase();delete v[e];delete u[b.pageurl];c.createarray("pano").removeItem(a);
p==a&&(p=K())}}else l("Remove Pano Error - Name must be specified.",3)}function L(a){if(J){var b=SWFAddress.getQueryString();SWFAddress.setValue(q(a)+(b?"?"+b:""))}}function I(a){SWFAddress.setValue(SWFAddress.getPath()+(a?"?"+a:""))}function y(){var a=SWFAddress.getBaseURL()+"#"+SWFAddress.getPath(),b=SWFAddress.getQueryString(),a=a+(b&&""!=b?"?"+SWFAddress.getQueryString():"");t?a=top.location.href?top.location.href:self.location.href:(b=window.location.href.toString())&&b!=a&&(a=b);return a}function r(a,
b,c,d){return a&&b?(a=a.replace(/\%PATH\%/g,b),a=a.replace(/\%PANOID\%/g,c?c:"null"),a=a.replace(/\%TYPE\%/g,d?d:"null")):null}function q(a){a="/"!=a.charAt(0)?"/"+a:a;"/"!=a.charAt(a.length-1)&&(a+="/");return a}function K(){var a=V("pano");if(a){var b=w(c.randomroot);return a?!b?A("pano",0).name:A("pano",Math.floor(Math.random()*(a-1-0+1))+0).name:null}return null}function V(a){return(a=c.createarray(a))?a.count:0}function n(a,b){var d=c.createarray(a);return b?d.getItem(b):null}function A(a,b){return c.createarray(a).getItem(b)}
function w(a){return"string"==typeof a||a instanceof String?a&&"true"==a.toLowerCase()?!0:!1:a}function h(a){return a&&a.length&&"null"!=a.toLowerCase()?a:null}function l(a,b,c){b=b||1;(c||3==b)&&d.call("showlog();");d.trace(b,W+": "+a)}var W="SWFAddress Plugin",G="1.3 (BETA 2)",J=!1,t=!1,S=/^get\(((?:.)+)\)$/i,v=null,u=null,p=null,H=null,d=null,c=null,x=null,z=null,k=null;this.registerplugin=function(a,b,e){d=a;x=b;c=e;if("1.0.8.14">d.version||"2011-05-20">d.build)d.trace(3,W+" - too old krpano version (min. 1.0.8.14 required)");
else{t=top===self?!1:!0;z=d.get("view");k=new BitlyService;l("v"+G);d.set(x+".keep",!0);d.set(x+".visible",!1);c.registerattribute("path",D(),m,D);c.registerattribute("title",M(),X,M);c.registerattribute("value",N(),f,N);c.registerattribute("baseurl",E(),f,E);c.registerattribute("fullurl",y(),f,Y);c.registerattribute("fullurlescaped",O(),f,O);c.registerattribute("viewurl",F(),f,F);c.registerattribute("viewurlescaped",P(),f,P);c.registerattribute("hasparams",Q(),f,Q);c.registerattribute("querystring",
R(),f,R);c.registerattribute("titleprefix",null);c.registerattribute("titlepostfix",null);c.registerattribute("randomroot",!1);c.registerattribute("onurlchange",null);c.registerattribute("onparamschange",null);c.registerattribute("onpathchange",null);c.registerattribute("bitlyapikey",null,Z,$);c.registerattribute("bitlylogin",null,aa,ba);c.registerattribute("onshortensuccess",null);c.registerattribute("onshortenerror",null);c.registerattribute("isiframe",t,f,ca);c.registerattribute("version",G,f,
da);k.onSuccess=B;k.onError=C;v={};u={};a=V("pano");var j,h,n;b=w(c.randomroot);for(var r,q=0;q<a;q++)e=A("pano",q),h=e.xmlurl||e.scene,r=e.scene?!0:!1,T(e.name,h,r,e.pageurl,e.pagetitle,e.onxmlcomplete,!1),h=w(e.root),!j&&h&&(n=e.name,j=!0);p=a?!b?n:A("pano",Math.floor(Math.random()*(a-1-0+1))+0).name:null;c.update=ea;c.addpano=fa;c.removepano=ga;c.removeallpanos=ha;c.shorten=ia;c.forcedispatchurlchange=ja;c.getparam=ka;c.setparam=la;c.setparams=ma;c.removeparams=na;c.replace=oa;c.replaceampersands=
pa;d.set("events[swfaddress].keep",!0);d.set("events[swfaddress].onxmlcomplete",x+".update();");SWFAddress.addEventListener(SWFAddressEvent.CHANGE,g);SWFAddress.addEventListener(SWFAddressEvent.EXTERNAL_CHANGE,s);J=!0;s(null);g(null)}};this.unloadplugin=function(){SWFAddress.removeEventListener(SWFAddressEvent.EXTERNAL_CHANGE,s);SWFAddress.removeEventListener(SWFAddressEvent.CHANGE,g);d.set("events[swfaddress].keep",!1);d.set("events[swfaddress].onxmlcomplete",null);urlToPanoIDMapping=panoIDToURLMapping=
null;J=!1;c=x=d=null}},BitlyService=function(){function g(B,C){this.login=C;this.apiKey=B;var f=this;this._callSuccess=function(g){null!=this.onSuccess&&this.onSuccess.call(null,g)};this._callError=function(g){null!=this.onError&&this.onError.call(null,g)};this._onHTTPReadyStateChanged=function(){if(4==this.readyState&&200==this.status){var m=JSON.parse(this.responseText);m&&"OK"==m.status_txt?f._callSuccess(m.data.url):f._callError(g.ERROR_SHORTEN_ERROR)}};this.shorten=function(f){f?!this.login||
!this.apiKey?this._callError(g.ERROR_LOGIN_OR_APIKEY_UNDEFINED):"file:"==window.location.protocol?this._callError(g.ERROR_WRONG_SANDBOX):(this._http=new XMLHttpRequest,f=f.replace(/\&amp\;/gi,"&"),f=s+"?longUrl="+escape(f)+"&login="+this.login+"&apiKey="+this.apiKey+"&format=json",this._http.open("GET",f,!0),this._http.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),this._http.onreadystatechange=this._onHTTPReadyStateChanged,this._http.send(null)):this._callError(g.ERROR_URL_UNDEFINED)}}
g.ERROR_URL_UNDEFINED=0;g.ERROR_LOGIN_OR_APIKEY_UNDEFINED=1;g.ERROR_WRONG_SANDBOX=2;g.ERROR_UNABLE_CONNECT_TO_SERVICE=3;g.ERROR_SHORTEN_ERROR=4;g.ERROR_UNKNOWN=5;var s="http://api.bit.ly/v3/shorten";return g}();